### ISSUE TITLE
Deprecate project

### ISSUE THREAD

**Issue by heldr** [heldr/gulp-smushit#2]
Yahoo stopped maintaining smush.it web service
http://www.phpied.com/smush-it-is-dead-long-live-smushing/

So, this project will be deprecated. :cry:

**Comment by KrunchMuffin** [comment]
why? just use this instead... http://www.resmush.it/

**Comment by heldr** [comment]
I didn't know about this service. Thank you!

**Comment by heldr** [comment]
@KrunchMuffin done! :tea:
